version: "25.0.2"
services:
  api:
    build: /
    container_name: thebombroms-server
    ports:
      - "3017:3017"
    volumes:
      - ./:/thebombroms-server
      - /node_modules
#     networks:
#       - docker-network
# networks:
#   docker-network:
#     external: true
