services:
  game-catalog-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: game-catalog-server
    ports:
      - "4010:4010"
    environment:
      - PORT=4010
    volumes:
      - ./:/game-catalog-server