services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: game-catalog-client
    ports:
      - "4009:4009"
    environment:
      - PORT=4009
    volumes:
      - ./:/game-catalog-client